### ISSUE TITLE
feat: app setup

### ISSUE THREAD

**Issue by mrcsilverfox** [wayt-travel/wayt_2.0#2]
- [x] feat: create auth and user repository
- [x] feat: add router
- [x] feat: add app bloc and all app initialisation logic
